export const CROP_OPTIONS = [
  "Avocado (Hass)",
  "Avocado (Fuerte)",
  "Mango (Apple)",
  "Mango (Kent)",
  "Mango (Ngowe)",
  "Pineapple",
  "Passion Fruit (Purple)",
  "Passion Fruit (Yellow)",
  "Banana",
  "Papaya",
  "Watermelon",
  "Lemon",
  "Lime",
  "Orange",
  "Grapes",
  "Strawberry",
  "Blueberry",
  "Apple",
  "Pear",
  "Pomegranate",
  "Macadamia",
  "Cashew Nut",
  "Coconut",
  "Casava",
  "Sweet Potato",
  "Potato",
  "Onion (Red)",
  "Onion (White)",
  "Garlic",
  "Ginger",
  "Turmeric",
  "Carrot",
  "French Beans",
  "Snow Peas",
  "Sugar Snap Peas",
  "Green Peas",
  "Broccoli",
  "Cauliflower",
  "Cabbage",
  "Spinach",
  "Kale (Sukuma Wiki)",
  "Tomato",
  "Cherry Tomato",
  "Chili (Bird Eye)",
  "Chili (Jalapeno)",
  "Capsicum (Green)",
  "Capsicum (Red)",
  "Cucumber",
  "Zucchini",
  "Eggplant",
  "Pumpkin",
  "Butternut",
  "Okra",
  "Asparagus",
  "Mushroom",
  "Maize",
  "Wheat",
  "Rice",
  "Sorghum",
  "Millet",
  "Pigeon Peas",
  "Green Gram",
  "Black Beans",
  "Red Kidney Beans",
  "Soybean",
  "Sesame",
  "Sunflower",
  "Coffee (Arabica)",
  "Coffee (Robusta)",
  "Tea",
  "Cocoa",
  "Cotton",
  "Pyrethrum",
  "Herbs (Basil)",
  "Herbs (Mint)",
  "Herbs (Coriander)",
  "Herbs (Rosemary)",
  "Herbs (Thyme)",
  "Flowers (Roses)",
  "Flowers (Carnations)",
];

export function inferCropCategory(cropName) {
  const value = String(cropName || "").toLowerCase();
  if (!value) return "";

  if (value.includes("coffee") || value.includes("tea") || value.includes("cocoa")) return "Beverage Crops";
  if (value.includes("rose") || value.includes("carnation") || value.includes("flowers")) return "Floriculture";
  if (value.includes("maize") || value.includes("wheat") || value.includes("rice") || value.includes("sorghum") || value.includes("millet")) return "Cereals";
  if (value.includes("bean") || value.includes("peas") || value.includes("gram") || value.includes("soy")) return "Legumes";
  if (value.includes("herbs") || value.includes("basil") || value.includes("mint") || value.includes("coriander") || value.includes("thyme") || value.includes("rosemary")) return "Herbs";
  if (value.includes("avocado") || value.includes("mango") || value.includes("pineapple") || value.includes("banana") || value.includes("papaya") || value.includes("lemon") || value.includes("lime") || value.includes("orange") || value.includes("grape") || value.includes("strawberry") || value.includes("blueberry") || value.includes("apple") || value.includes("pear") || value.includes("pomegranate") || value.includes("passion")) return "Fruits";
  if (value.includes("potato") || value.includes("onion") || value.includes("garlic") || value.includes("ginger") || value.includes("turmeric") || value.includes("carrot") || value.includes("broccoli") || value.includes("cauliflower") || value.includes("cabbage") || value.includes("spinach") || value.includes("kale") || value.includes("tomato") || value.includes("chili") || value.includes("capsicum") || value.includes("cucumber") || value.includes("zucchini") || value.includes("eggplant") || value.includes("pumpkin") || value.includes("butternut") || value.includes("okra") || value.includes("asparagus") || value.includes("mushroom") || value.includes("french beans") || value.includes("snow peas") || value.includes("snap peas")) return "Vegetables";
  if (value.includes("macadamia") || value.includes("cashew") || value.includes("coconut") || value.includes("sesame") || value.includes("sunflower")) return "Nuts & Oilseeds";
  return "Other";
}
